== Collaborative Georeferencing

The characteristics that make a <<georeference,georeferencing>> project collaborative are the aggregation of occurrence records from multiple participating groups (e.g. datasets, collections, institutions), the extraction of distinct <<locality,localities>> as the actual target of georeferencing, the standardization of the geography of the aggregated records to aid record grouping and assignment by geography.

Collaborative georeferencing, if done properly, can have definitive advantages over georeferencing alone. MaNIS (http://georeferencing.org/georefcalculator/docs/GeorefGuide.html[Wieczorek 2001^]) and Australia's Virtual Herbarium (https://www.anbg.gov.au/chah/avh/avh.html[ANBG 2018]) found that collaborative georeferencing resulted in great efficiency gains, but that including validation checks afterwards by reviewing the records using collector and date, or looking at the records taxonomically to check for outliers, and other such <<data quality>> flags, is important. Advantages and disadvantages of collaborative georeferencing, adapted from http://georeferencing.org/manis/GeorefCollaboration021021.ppt[Wieczorek & Beaman 2002^] and https://doi.org/10.17161/bi.v1i0.7[Stein & Wieczorek 2004^] include:

*Advantages*

* Reduces overall cost of supplies (e.g. maps) – no duplication.
* Expands the pool of resources – geographic expertise and reference materials.
* Takes advantage of regional expertise, knowledge, language skills and resources.
* Increases georeferencing rates – economy of scale.
* Promotes standardization of methods.
* Increases skills in a community.
* Increases exposure and awareness inside and outside of a community － strengthens community relationships.

*Disadvantages*

* Vulnerable to procrastination, delays, uneven levels of training, expertise and commitment.
* Can distance the georeferencing process from useful primary resources (e.g. specimen labels and field notes).
* Introduces time sensitivity to the georeferencing process (locality information for the underlying occurrence records might be subject to changes during the georeferencing process that would render a different result).
* Data repatriation into the originating collection can be a difficult and time-consuming process.
* Requires project-level management.
* Requires a formalized validation process.

One of the greatest impediments to effective collaborative georeferencing, is the absence of tools to easily <<repatriate>> the georeferenced information back to the data sources (https://doi.org/10.3897/zookeys.209.3205[Barkwell and Murrell 2012^], https://doi.org/10.3897/biss.2.26479[Grant et al. 2018^]). A number of projects are working on this, especially <<GEOLocate>> in conjunction with the Symbiota platform (https://doi.org/10.3897/BDJ.2.e1114[Gries et al. 2014^]). It is hoped that this document will provide consistency of methodology and documentation and lead to more collaborative <<georeference,georeferencing>>.

Some organizations, such as DigiVol (https://digivol.ala.org.au/[Australian Museum n.d.^]) and Notes from Nature https://www.zooniverse.org/organizations/md68135/notes-from-nature[(Zooniverse _n.d.)] use crowdsourcing to <<georeference>>, whereas projects like CoGeo (part of GEOLocate, https://coge.geo-locate.org/[GEOLocate 2018^]), are more constrained in their participants.

[[digivol]]
=== DigiVol

The http://www.ala.org.au/[Atlas of Living Australia], in collaboration with the http://australianmuseum.net.au/[Australian Museum], developed DigiVol (http://volunteer.ala.org.au/[Australian Museum n.d.]) to harness the power of online volunteers (also known as crowdsourcing) to digitize biodiversity data that is locked up in biodiversity collections, field notebooks and survey sheets. Although originally developed in Australia, DigiVol has many projects and expeditions from all over the globe. Not all DigiVol projects (called expeditions) include a <<georeference,georeferencing>> component, but some of them do, and there is no reason that there won’t be more in the future. 

The Australian Museum has developed a guide for a mapping tool to use with DigiVol (https://volunteer.ala.org.au/data/volunteer/tutorials/Australian%20Museum%20Tutorials_Mapping%20Tool%20Tutorial.pdf[Edey _n.d.^]). The mapping tool, however, has a number of features that we would not recommend. Default positions are given for the "center" of a number of Australian States without an appropriate associated <<uncertainty>> value. The uncertainty of the georeference is added by a pulldown menu that gives three options: 1km, 5km and 10km. Our recommendation would be to make <<uncertainty>> continuous–possibly by selection on the map, or calculated using the body of information in this document, the protocols of the {gqg}[Georeferencing Quick Reference Guide] (Zermoglio et al. 2020), and the algorithms of the {gcm}[Georeferencing Calculator] (Wieczorek & Wieczorek 2020).

=== Notes from Nature

The Notes from Nature project (https://www.notesfromnature.org/[Zooniverse n.d.^]) gives people the opportunity to make scientifically important contributions toward the goal of conserving and making available knowledge about natural and cultural heritage. "Every transcription that is completed brings us closer to filling gaps in our knowledge of global biodiversity and natural heritage". It is very similar to <<digivol,DigiVol>>. Currently, there are no <<georeference,georeferencing>> projects (expeditions) in Notes from Nature, but there are plans to develop this in the future.

=== GEOLocate

The GEOLocate suite of tools includes a web-based collaborative client – CoGeo (https://coge.geo-locate.org/[Rios 2019^]), the goal of which is to provide a mechanism whereby groups of users can form communities to collaboratively <<georeference>> and verify a shared dataset (http://www.geo-locate.org/community/default.html[GEOLocate 2018^]). This allows for the upload of a CSV file and having parts of the dataset allocated to a user. GEOLocate can also be accessed through third party applications via its API.

Using the tools in GEOLocate, a <<georeference>> may be determined along with an <<uncertainty>> (Biedron and Famoso 2016). An <<uncertainty>> polygon (see also <<shape>> and <<Shape Method>>) can also be drawn in addition to the <<point-radius>> circle. Note that GEOLocate may return more than one candidate <<location>> for a given <<locality>> string and users are advised to always verify and adjust, as needed, to obtain the final accepted result (including uncertainty <<radial,radii>> and polygons). The data can be exported through KML for plotting onto Google Earth. The system allows for review of records and we recommend that this be done for all records where possible.

=== Other Collaborative Georeferencing Projects

Other projects, including the terrestrial vertebrate precursor projects to VertNet (https://doi.org/10.17161/bi.v1i0.7[Stein and Wieczorek 2004^], https://doi.org/10.1525/bio.2010.60.4.2[Guralnick and Constable 2010^]), have, in the past, divided up and distributed the records for <<locality,localities>> from a given geographic region to an institution with expertise in and/or resources about that region to <<georeference>> (see <<Project Workflow Example – MaNIS/HerpNET/ORNIS>>). The major advantages of this approach are that the quantity and <<data quality,quality>> of the raw materials used for georeferencing are probably higher, and the efficiency and quality of the results are also likely higher than if attempted without taking advantage of these resources. However, as mentioned earlier, <<repatriate,repatriation>> of the georeferenced records is an issue that needs solving for this to work most efficiently.
