== Sharing Data

<<georeference,Georeferencing>> is only the first step toward making biological (specimen and observation) data available to the world. However, it is an important first step, as it is one of the two most key methods for identifying what and where a specimen is, _viz._ its scientific name and its location (Chapman 2005a). Two main standards have been developed for sharing biological data, <<Darwin Core>> (Wieczorek _et al._ 2012b) and https://www.tdwg.org/standards/abcd/[Access to Biological Collections Data] (ABCD), both ratified by https://www.tdwg.org/[Biodiversity Information Standards] (TDWG). We do not treat the ABCD standard separately in this document, as https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv[term mappings between Darwin Core and ABCD are well defined] for location data. One of the principles of <<Darwin Core>> is to try to provide content for every field possible.

=== Mapping to Darwin Core

The <<Darwin Core>> (denoted with the abbreviated namespace `_dwc_`) <<georeference,georeferencing>> concepts that are directly used in this document are:

http://rs.tdwg.org/dwc/terms/#decimalLatitude[`_dwc:decimalLatitude_`], http://rs.tdwg.org/dwc/terms/#decimalLongitude[`_dwc:decimalLongitude_`]:: the <<geographic coordinates>> of the center of the <<point-radius>> version of the <<georeference>>

http://rs.tdwg.org/dwc/terms/#geodeticDatum[`_dwc:geodeticDatum_`]:: the <<EPSG>> code (preferably) or name of the <<coordinate reference system>>, <<geodetic datum>>, or <<ellipsoid>> of the <<point-radius>> version of the <<georeference>>

http://rs.tdwg.org/dwc/terms/#coordinateUncertaintyInMeters[`_dwc:coordinateUncertaintyInMeters_`]:: the <<radial>> of the <<point-radius>> version of the <<uncertainty>> of the <<georeference>>, in meters

http://rs.tdwg.org/dwc/terms/#coordinatePrecision[`_dwc:coordinatePrecision_`]:: the decimal representation of the <<precision>> of the output <<coordinates>> of the <<georeference>>

http://rs.tdwg.org/dwc/terms/#footprintWKT[`_dwc:footprintWKT_`]:: the representation of the resulting <<shape>> or <<bounding box>> <<georeference>>, in Well-Known Text (WKT, ISO 2016)

http://rs.tdwg.org/dwc/terms/#footprintSRS[`_dwc:footprintSRS_`]:: the <<coordinate reference system>> of the resulting <<shape>> or <<bounding box>> <<georeference>>, in Well-Known Text (WKT, ISO 2016)

http://rs.tdwg.org/dwc/terms/#locality[`_dwc:locality_`]:: intended to contain a version (perhaps modified from the original) of the parts of the textual description of the <<location>> that do not have another <<Darwin Core>> term appropriate to hold them; in legacy data, may contain any textual information about the <<location>>

http://rs.tdwg.org/dwc/terms/#verbatimLocality[`_dwc:verbatimLocality_`]:: meant to contain all of the unmodified original <<location>> information

http://rs.tdwg.org/dwc/terms/#verbatimCoordinates[`_dwc:verbatimCoordinates_`]:: the original <<coordinates>> in the original format, especially if they are not <<latitude>> and <<longitude>>, such as <<UTM>> <<coordinates>>

http://rs.tdwg.org/dwc/terms/#verbatimLatitude[`_dwc:verbatimLatitude_`], http://rs.tdwg.org/dwc/terms/#verbatimLongitude[`_dwc:verbatimLongitude_`]:: the original <<latitude>> and <<longitude>> in the original format

http://rs.tdwg.org/dwc/terms/#verbatimCoordinateSystem[`_dwc:verbatimCoordinateSystem_`]:: the <<coordinate format>> of the <<coordinates>> that are either in `_dwc:verbatimCoordinates_` or in `_dwc:verbatimLatitude_` and `_dwc:verbatimLongitude_`

http://rs.tdwg.org/dwc/terms/#verbatimSRS[`_dwc:verbatimSRS_`]:: the <<coordinate reference system>> of either the `_dwc:verbatimCoordinates_` or the combination of `_dwc:verbatimLatitude_` and `_dwc:verbatimLongitude_`

http://rs.tdwg.org/dwc/terms/#minimumElevationInMeters[`_dwc:minimumElevationInMeters_`], http://rs.tdwg.org/dwc/terms/#maximumElevationInMeters[`_dwc:maximumElevationInMeters_`]:: the lower and upper limits of the <<elevation>> of the <<location>>, in meters

http://rs.tdwg.org/dwc/terms/#verbatimElevation[`_dwc:verbatimElevation_`]:: the original <<elevation>> in the original format with the original units

http://rs.tdwg.org/dwc/terms/#minimumDepthInMeters[`_dwc:minimumDepthInMeters_`], http://rs.tdwg.org/dwc/terms/#maximumDepthInMeters[`_dwc:maximumDepthInMeters_`]:: the minimum and maximum limits of the <<depth>> of the <<location>>, in meters

http://rs.tdwg.org/dwc/terms/#verbatimDepth[`_dwc:verbatimDepth_`]:: the original <<depth>> in the original format with the original units

http://rs.tdwg.org/dwc/terms/#minimumDistanceAboveSurfaceInMeters[`_dwc:minimumDistanceAboveSurfaceInMeters_`], http://rs.tdwg.org/dwc/terms/#maximumDistanceAboveSurfaceInMeters[`_dwc:maximumDistanceAboveSurfaceInMeters_`]:: the lower and upper limits of the position with respect to a local surface, either at an <<elevation>>, or at a <<depth>> from an <<elevation>>.

http://rs.tdwg.org/dwc/terms/#locationAccordingTo[`_dwc:locationAccordingTo_`]:: the source authority for the <<location>> information, not the <<georeference>> information, for which see `_dwc:georeferenceSources_`

http://rs.tdwg.org/dwc/terms/#locationRemarks[`_dwc:locationRemarks_`]:: comments about the <<location>> information, not about the <<georeference>> for the <<location>>, for which see `_dwc:georeferenceRemarks_`

http://rs.tdwg.org/dwc/terms/#pointRadiusSpatialFit[`_dwc:pointRadiusSpatialFit_`]:: the <<spatial fit>> of the <<point-radius>> <<georeference>> (see <<Determining Spatial Fit>>)

http://rs.tdwg.org/dwc/terms/#footprintSpatialFit[`_dwc:footprintSpatialFit_`]:: the <<spatial fit>> of the <<shape>> or <<bounding box>> <<georeference>> (see <<Determining Spatial Fit>>)

http://rs.tdwg.org/dwc/terms/#georeferencedBy[`_dwc:georeferencedBy_`]:: who is responsible for the <<georeference>> as it currently stands, could be the person who did the first pass, but could be changed later to the person who verifies it

http://rs.tdwg.org/dwc/terms/#georeferencedDate[`_dwc:georeferencedDate_`]:: the date on which the data in the <<georeference>> fields reached their current state

http://rs.tdwg.org/dwc/terms/#georeferenceProtocol[`_dwc:georeferenceProtocol_`]:: a citation of a published set of rules used to determine a <<georeference>>. For example, "`_Georeferencing Quick Reference Guide_` Version 2019-11-08". Any deviations from the cited protocol should be noted in `_dwc:georeferenceRemarks_`

http://rs.tdwg.org/dwc/terms/#georeferenceSources[`_dwc:georeferenceSources_`]:: a list of maps, <<gazetteer,gazetteers>>, or other resources used to <<georeference>> the <<locality>>. Should be specific enough that someone else can locate and use the same sources. Example: "USGS 1:24000 Florence Montana Quad; Terrametrics 2008, Google Earth™".

http://rs.tdwg.org/dwc/terms/#georeferenceVerificationStatus[`_dwc:georeferenceVerificationStatus_`]:: an indicator of the extent to which the <<georeference>> has been verified to represent the best possible spatial description for the occurrence record. By default a newly created <<georeference>> should have the status "requires verification". Beyond that, there are really only two other functionally distinct possibilities, either "verified" (by the person mentioned in `_dwc:georeferencedBy_`), and "verified by collector" or equivalent, to designate that the <<georeference>> was reviewed for that specific record by the person who recorded it to begin with, and that it can not be further improved. This is the ideal status to aspire to.

http://rs.tdwg.org/dwc/terms/#georeferenceRemarks[`_dwc:georeferenceRemarks_`]:: any notes or comments about the spatial description, deviations from the cited protocol, assumptions, or problems with <<georeference,georeferencing>>. For example, "locality too vague to georeference".

=== Generalizing Georeferences for Sensitive Taxa and Locations

As recommended elsewhere in this document, <<georeference,georeferences>> should be recorded and stored at the best possible resolution and <<precision>>. If, however, the <<location>> of a taxon is regarded as sensitive for some reason following the guidelines as set out in Chapman (2020), and Chapman & Grafton (2008), and it is agreed that the detailed <<location>> information should not be shared, we recommend, that the data only be <<generalization,generalized>> at the time of sharing or publishing of the data.

We recommend that if data are to be <<generalization,generalized>> that it be done by reducing the number of decimal places (for example when using <<decimal degrees>>) at which the data are published (Chapman & Grafton 2008, Chapman 2020). Good practice dictates that whatever you do to <<generalization,generalize>> the data, it be documented so that users of the data know what reliance can be placed on them. As far as the <<generalization>> of <<georeference,georeferencing>> data is concerned it is important to record that the data have been <<generalization,generalized>> using a ‘_decimal geographic grid_’, and record both:

* <<precision,Precision>> of the data provided (_e.g._, 0.1 degree; 0.001 degree, etc.)
* <<precision,Precision>> of the data stored or held (_e.g._, 0.0001 degree, 0.1 minute, 1 second, etc.)

We recommend that when recording the degree of <<generalization>> of data, that <<spatial fit,Spatial Fit>> (<<Determining Spatial Fit>>) be used. For example, the degree to which a record has been <<generalization,generalized>> to obfuscate the <<georeference>> will be a number greater than 1 (see xref:img-spatial-fit[xrefstyle="short"] and Chapman 2020).

NOTE: Data should never be <<generalization,generalized>> at the time of collection, when <<georeference,georeferencing>>, or when storing in the database.

Some institutions randomize the data before publishing. This is a practice we do *_NOT_* recommend, and in fact would discourage it in all circumstances (Chapman 2020).
