== Sharing Data

<<georeference,Georeferencing>> is only the first step toward making biological (specimen and observation) data available to the world. However, it is an important first step, as it is one of the two most key methods for identifying what and where a specimen is, that is, its scientific name and its location (https://doi.org/10.15468/doc.jrgg-a190[Chapman 2005a^]). Two main standards have been developed for sharing biological data, <<Darwin Core>> (https://doi.org/10.1371/journal.pone.0029715[Wieczorek et al. 2012b^]) and https://www.tdwg.org/standards/abcd/[Access to Biological Collections Data^] (ABCD), both ratified by https://www.tdwg.org/[Biodiversity Information Standards^] (TDWG). We do not treat the ABCD standard separately in this document, as https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv[term mappings between Darwin Core and ABCD are well defined^] for location data. One of the principles of <<Darwin Core>> is to try to provide content for every field possible.

=== Mapping to Darwin Core

The <<Darwin Core>> (denoted with the abbreviated namespace [.term]#dwc#) <<georeference,georeferencing>> concepts that are directly used in this document are:

term:dwc[dwc:decimalLatitude], term:dwc[dwc:decimalLongitude]:: the <<geographic coordinates>> of the center of the <<point-radius>> version of the <<georeference>>

term:dwc[dwc:geodeticDatum]:: the <<EPSG>> code (preferably) or name of the <<coordinate reference system>>, <<geodetic datum>>, or <<ellipsoid>> of the <<point-radius>> version of the <<georeference>>

term:dwc[dwc:coordinateUncertaintyInMeters]:: the <<radial>> of the <<point-radius>> version of the <<uncertainty>> of the <<georeference>>, in meters

term:dwc[dwc:coordinatePrecision]:: the decimal representation of the <<precision>> of the output <<coordinates>> of the <<georeference>>

term:dwc[dwc:footprintWKT]:: the representation of the resulting <<shape>> or <<bounding-box>> <<georeference>>, in Well-Known Text (WKT) (https://www.iso.org/standard/60343.html[ISO 2016^])

term:dwc[dwc:footprintSRS]:: the <<coordinate reference system>> of the resulting <<shape>> or <<bounding-box>> <<georeference>>, in Well-Known Text (WKT) (https://www.iso.org/standard/60343.html[ISO 2016^])

term:dwc[dwc:locality]:: intended to contain a version (perhaps modified from the original) of the parts of the textual description of the <<location>> that do not have another <<Darwin Core>> term appropriate to hold them; in legacy data, may contain any textual information about the location

term:dwc[dwc:verbatimLocality]:: meant to contain all of the unmodified original <<location>> information

term:dwc[dwc:verbatimCoordinates]:: the original <<coordinates>> in the original format, especially if they are not <<latitude>> and <<longitude>>, such as <<UTM>> coordinates

term:dwc[dwc:verbatimLatitude], term:dwc[dwc:verbatimLongitude]:: the original <<latitude>> and <<longitude>> in the original format

term:dwc[dwc:verbatimCoordinateSystem]:: the <<coordinate format>> of the <<coordinates>> that are either in term:dwc[dwc:verbatimCoordinates] or in term:dwc[dwc:verbatimLatitude] and term:dwc[dwc:verbatimLongitude]

term:dwc[dwc:verbatimSRS]:: the <<coordinate reference system>> of either the term:dwc[dwc:verbatimCoordinates] or the combination of term:dwc[dwc:verbatimLatitude] and term:dwc[dwc:verbatimLongitude]

term:dwc[dwc:minimumElevationInMeters], term:dwc[dwc:maximumElevationInMeters]:: the lower and upper limits of the <<elevation>> of the <<location>>, in meters

term:dwc[dwc:verbatimElevation]:: the original <<elevation>> in the original format with the original units

term:dwc[dwc:minimumDepthInMeters], term:dwc[dwc:maximumDepthInMeters]:: the minimum and maximum limits of the <<depth>> of the <<location>>, in meters

term:dwc[dwc:verbatimDepth]:: the original <<depth>> in the original format with the original units

term:dwc[dwc:minimumDistanceAboveSurfaceInMeters], term:dwc[dwc:maximumDistanceAboveSurfaceInMeters]:: the lower and upper limits of the position with respect to a local surface, either at an <<elevation>>, or at a <<depth>> from an <<elevation>>.

term:dwc[dwc:locationAccordingTo]:: the source authority for the <<location>> information, not the <<georeference>> information, for which see term:dwc[dwc:georeferenceSources]

term:dwc[dwc:locationRemarks]:: comments about the <<location>> information, not about the <<georeference>> for the location, for which see term:dwc[dwc:georeferenceRemarks]

term:dwc[dwc:pointRadiusSpatialFit]:: the <<spatial fit>> of the <<point-radius>> <<georeference>> (see <<Determining Spatial Fit>>)

term:dwc[dwc:footprintSpatialFit]:: the <<spatial fit>> of the <<shape>> or <<bounding-box>> <<georeference>> (see <<Determining Spatial Fit>>)

term:dwc[dwc:georeferencedBy]:: who is responsible for the <<georeference>> as it currently stands, could be the person who did the first pass, but could be changed later to the person who verifies it

term:dwc[dwc:georeferencedDate]:: the date on which the data in the <<georeference>> fields reached their current state

term:dwc[dwc:georeferenceProtocol]:: a citation of a published set of rules used to determine a <<georeference>>. For example, “Georeferencing Quick Reference Guide Version 2019-11-08”. Any deviations from the cited protocol should be noted in term:dwc[dwc:georeferenceRemarks]

term:dwc[dwc:georeferenceSources]:: a list of maps, <<gazetteer,gazetteers>>, or other resources used to <<georeference>> the <<locality>>. Should be specific enough that someone else can locate and use the same sources. Example: "USGS 1:24000 Florence Montana Quad; Terrametrics 2008, Google Earth™".

term:dwc[dwc:georeferenceVerificationStatus]:: an indicator of the extent to which the <<georeference>> has been verified to represent the best possible spatial description for the occurrence record. By default a newly created georeference should have the status "requires verification". Beyond that, there are really only two other functionally distinct possibilities, either "verified" (by the person mentioned in term:dwc[dwc:georeferencedBy]), and "verified by collector" or equivalent, to designate that the georeference was reviewed for that specific record by the person who recorded it to begin with, and that it can not be further improved. This is the ideal status to aspire to.

term:dwc[dwc:georeferenceRemarks]:: any notes or comments about the spatial description, deviations from the cited protocol, assumptions, or problems with <<georeference,georeferencing>>. For example, "locality too vague to georeference".

=== Generalizing Georeferences for Sensitive Taxa and Locations

As recommended elsewhere in this document, <<georeference,georeferences>> should be recorded and stored at the best possible resolution and <<precision>>. If, however, the <<location>> of a taxon is regarded as sensitive for some reason following the guidelines as set out in https://doi.org/10.15468/doc-5jp4-5g10[Chapman 2020^] and https://doi.org/10.15468/doc-b02j-gt10[Chapman & Grafton 2008^], and it is agreed that the detailed location information should not be shared, we recommend, that the data only be <<generalization,generalized>> at the time of sharing or publishing of the data.

We recommend that if data are to be generalized that it be done by reducing the number of decimal places (for example when using <<decimal degrees>>) at which the data are published (https://doi.org/10.15468/doc-b02j-gt10[Chapman & Grafton 2008^], https://doi.org/10.15468/doc-5jp4-5g10[Chapman 2020^]). Good practice dictates that whatever you do to generalize the data, it be documented so that users of the data know what reliance can be placed on them. As far as the generalization of georeferencing data is concerned it is important to record that the data have been generalized using a ‘_decimal geographic grid_’, and record both:

* Precision of the data provided (e.g. 0.1 degree; 0.001 degree, etc.)
* Precision of the data stored or held (e.g. 0.0001 degree, 0.1 minute, 1 second, etc.)

We recommend that when recording the degree of generalization of data, that <<spatial fit,Spatial Fit>> (<<Determining Spatial Fit>>) be used. For example, the degree to which a record has been generalized to obfuscate the georeference will be a number greater than 1 (see xref:img-spatial-fit[xrefstyle="short"] and https://doi.org/10.15468/doc-5jp4-5g10[Chapman 2020^]).

NOTE: Data should never be generalized at the time of collection, when georeferencing or when storing in the database.

Some institutions randomize the data before publishing. This is a practice we do *NOT* recommend, and in fact would discourage it in all circumstances (https://doi.org/10.15468/doc-5jp4-5g10[Chapman 2020^]).
