== Acknowledgements

Many people have contributed ideas to this document and its precursors, either directly or indirectly through discussions at meetings, publications, or in email correspondence. We refer you to the earlier document for those we acknowledged there.

The people we would like to particularly acknowledge for this document, include Paula F. Zermoglio, David Bloom, Deborah Paul, Nelson Rios, Lee Belbin, Paul J. Morris, Alex Thompson, Ward Appeltens, Sarah Gilbert, Robert Kershaw, Arturo H. Ariño, Arnald Marcer, Dimitris Koureas and members of the TDWG Data Quality Interest Group, Task Group 2 as well as staff at the GBIF Secretariat, especially Laura Russell, Kyle Copas, and Matthew Blissett who provided support for the project. Members of the Paleo community, especially Talia Karim and Jessica Bazeley, provided valuable feedback on topics of particular interest to that community. Special mention must be made of Alejandro Tablado for "complaining" in the GBIF Georeferencing Workshop in Buenos Aires in 2006 about the lack of treatment of marine considerations in the first version of the Best Practices Guide. The suggestion was much appreciated. We hope that the current document makes up for our lack of attention to the topic in the earlier version.
