files:
  - source: /translations/index.pot
    translation: /translations/%two_letters_code%.po
  - source: /**/*.en.adoc
    translation: /translations/%file_name%.%two_letters_code%.adoc
    translation_replace:
      ".en.": "."
