== Acknowledgements

Many people have contributed ideas to this document and its precursors, either directly or indirectly through discussions at meetings, publications, or in email correspondence. We refer you to the earlier document for those we acknowledged there.

The people we would like to particularly acknowledge for this document include Ward Appeltens, Arturo H. Ariño, Lee Belbin, Matt Blissett, David Bloom, David Fichtmüller, Ricardo Ortiz Gallego, Sarah Gilbert, Quentin Groom, Robert Kershaw, Kyle Copas, Dimitris Koureas, Celeste Luna, Arnald Marcer, Paul J. Morris, Deborah Paul, Nelson Rios, Alex Thompson, and Paula F. Zermoglio. We would further like to acknowledge members of the TDWG Data Quality Interest Group, Task Group 2 and staff at the GBIF Secretariat, especially Laura Russell, Kyle Copas, and Matthew Blissett who provided support for the project in which this document was solicited. Members of the Paleo community, especially Talia Karim and Jessica Bazeley, provided valuable feedback on topics of particular interest to that community. Special mention must be made of Alejandro Tablado for "complaining" in the GBIF Georeferencing Workshop in Buenos Aires in 2006 about the lack of treatment of marine considerations in the first version of the Best Practices Guide. The suggestion was much appreciated. We hope that the current document makes up for our lack of attention to the topic in the earlier version.



